//@version=5
strategy(title="Grid Trading Strategy", overlay = true, pyramiding = 14, close_entries_rule = 'ANY',  initial_capital = 1000)

// Youtuber: Financial Programming with Ritvik, CFA
// Reference: https://www.youtube.com/watch?v=IbkHMgJ3vZs&list=PLxvRLWqiBMjrRz_LUBCHJk-xZeAjavtCN&index=3

// Input
ma_length = input.int(300, 'MA length', group = 'Moving Avg Conditions', step = 10)
std = input.float(0.03, title = 'Upper and Lower Grid Deviation', group = 'Grid Conditions', step = 0.01)
grids = input.int(15, maxval = 15, title = 'Grid Line Quantity', group = 'Grid Conditions')

// Moving Average 
ma = ta.sma(close, ma_length)
uppper_bound = ma * (1 + std)
lower_bound = ma * (1 - std)
grid_width = (uppper_bound - lower_bound) / (grids - 1)

grid_array = array.new_float(0)
for i = 0 to grids - 1 by 1
	array.push(grid_array, lower_bound + grid_width * i)

var order_array = array.new_bool(grids,false)

// Entry Conditions
for i  = 0 to grids - 1 by 1 
	if close < array.get(grid_array, i) and not array.get(order_array, i)
		buy_id = i
		array.set(order_array, buy_id, true)
		strategy.entry(id = str.tostring(buy_id), direction = strategy.long, qty = strategy.initial_capital / (grids - 1), comment='#Long ' + str.tostring(buy_id))
	if close > array.get(grid_array, i) and i != 0
		if array.get(order_array, i - 1)
			sell_id = i - 1
			array.set(order_array, sell_id, false)
			strategy.close(id = str.tostring(sell_id), comment = '#Close ' + str.tostring(sell_id))


// Plot 
plot(grids > 0 ? array.get(grid_array, 0) : na, color = color.yellow)
plot(grids > 1 ? array.get(grid_array, 1) : na, color = color.yellow)